# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0003_auto_20171026_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
