# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0004_auto_20171026_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 26, 23, 47, 34, 912722, tzinfo=utc)),
        ),
    ]
