# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0006_auto_20171101_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 11, 2, 1, 3, 24, 417976, tzinfo=utc)),
        ),
    ]
